name: final-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas>=2.2.0
  - numpy>=2.1.0
  - scikit-learn>=1.5.0
  - xgboost>=2.1.0
  - pytest>=8.0.0
  - pip
pip:
      - arch>=7.2.0
      - yfinance>=0.2.50 

